service: backend-aws

provider:
  name: aws
  runtime: python3.7

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["dataTable", "Arn" ] }

functions:
  get_data:
    handler: handler.get_data
    events:
      - http:
          path: data
          method: get
          cors: true
  store_data:
    handler: handler.store_data
    events:
      - http:
          path: data
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials

resources:
 Resources:
   dataTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: data-table
        AttributeDefinitions:
          - 
            AttributeName: dataId
            AttributeType: S
        KeySchema:
          - 
            AttributeName: dataId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
